title: wemble
url: https://wemble.com

include:
  - _redirects

exclude:
  - wrangler.jsonc
  - Gemfile
  - Gemfile.lock
  - conf.d
  - README.md
  - LICENSE
  - Dockerfile
  - index_now.sh
  - .claude
  - assets/images
  - dist
