server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /www;
	index index.html;

	location = /favicon.ico { return 301 /favicon.png; }

	# Old catalog, blog, and aliases
	location /stuff { return 301 /; }
	location /things { return 301 /; }
	location /blog { return 301 /; }
	location /products { return 301 /; }
	location /work { return 301 /; }
	location /contact { return 301 /; }
	location /company { return 301 /; }
	location /posts { return 301 /; }
	location /2024 { return 301 /; }
	location /2026 { return 301 /; }

	location / {
		try_files $uri $uri/ =404;
	}
}
